### ISSUE TITLE
async actions

### ISSUE THREAD

**Issue by ariesshrimp** [Emilios1995/redux-create-module#2]
it doesn't look like this will handle asynchronous actions without another library's help like saga or thunk. but it's nice to be able to handle network requests in your actions without an added dependancy

**Comment by langpavel** [comment]
As you can see in source, entire module is only 19 SLoC. You will get another dependency which introduce new blackbox and you loss declarative action naming in one place which is most positive thing on redux.
**Because redux is about single point of dispatching every possible event**

**Comment by Emilios1995** [comment]
@langpavel is right. this module has to stay small to remain true to its purpose.
